---
title: "A model of Calluna production decision"
author: "Marius Rütt, Cory Whitney"
date: "1/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(signal)
library(DAutilities)
library(Surrogate)
library(decisionSupport)
library(tidyverse)
library(knitr)
library(kableExtra)
options(knitr.table.format = "html")
```

The input table is ...
```{r}
input_table <- read.csv("Calluna_low_prophy.csv")
input_table <-select(input_table, -X, -General.variables, - Description, - median)
kable(input_table)%>%
  kable_styling(bootstrap_options = c("striped", "hover")) 
```  

Load the input table and make variables. The rest of the calculations in this doument will be based on random draws from the distributions in the input table `Calluna_low_prophy.csv`.
```{r}
input_table <- "Calluna_low_prophy.csv"

make_variables <- function(est,n=1)
{ x <- random(rho=est, n=n)
for(i in colnames(x)) assign(i, as.numeric(x[1,i]),envir = .GlobalEnv)}

make_variables(estimate_read_csv(input_table))

```

## Calluna function in `decisionSupport`

Calculate the number of plants in the whole production area
```{r}
  original_plant_number <- production_area * plants_per_ha

  original_plant_number
```
Define risky months (May to August) 
```{r}
  weather_arguments_for_infection <- c(0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0)
```
